### ISSUE TITLE
MPE broken on OSX

### ISSUE THREAD

**Issue by rturknett** [TACC/MassivePixelEnvironment#22]
Can't run MPE sketches where processes ssh to localhost on OSX. Debug output when running MPEPeasy.pde with configuration_localhost.xml:

loading XML configuration node
loading XML dimensions node
loading XML dimensions node, screenWidth
loading XML dimensions node, mullionHeight
loading XML dimensions node, debug
numFollowers_ = 4
loading XML dimensions node, head
Server: localhost:9002
loading XML configuration node
loading XML dimensions node
loading XML dimensions node, screenWidth
loading XML dimensions node, mullionHeight
loading XML dimensions node, debug
numFollowers_ = 4
loading XML dimensions node, head
Server: localhost:9002
-1: Number of followers: 4
Setting window location to: 0, 0
Settings: Rank: -1, offsets: 0,0, lDims: 400,400, mDims: 400,400, windowLocation: 0,0
PeasyCam v200
AutoLauncher:loading XML configuration node
AutoLauncher:loading XML processingPath node
processingPath = /usr/bin/

localhost-rank2: java.awt.HeadlessException: 
localhost-rank1: java.awt.HeadlessException: 
localhost-rank2: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
localhost-rank1: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
localhost-rank1:    at sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(HeadlessGraphicsEnvironment.java:72)
localhost-rank3: java.awt.HeadlessException: 
localhost-rank1:    at processing.core.PApplet.runSketch(PApplet.java:10482)
localhost-rank2:    at sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(HeadlessGraphicsEnvironment.java:72)
localhost-rank2:    at processing.core.PApplet.runSketch(PApplet.java:10482)
localhost-rank2:    at processing.core.PApplet.main(PApplet.java:10377)
localhost-rank1:    at processing.core.PApplet.main(PApplet.java:10377)
localhost-rank4: java.awt.HeadlessException: 
localhost-rank3: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
localhost-rank4: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
localhost-rank3:    at sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(HeadlessGraphicsEnvironment.java:72)
localhost-rank4:    at sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(HeadlessGraphicsEnvironment.java:72)
localhost-rank3:    at processing.core.PApplet.runSketch(PApplet.java:10482)
localhost-rank4:    at processing.core.PApplet.runSketch(PApplet.java:10482)
localhost-rank3:    at processing.core.PApplet.main(PApplet.java:10377)
localhost-rank4:    at processing.core.PApplet.main(PApplet.java:10377)

**Comment by rturknett** [comment]
Tested this today -- replicated issue by running ssh localhost, setting the DISPLAY variable, and launching a simple Processing sketch. Also fails when doing the same from a remote host:

`java.awt.HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it.`

NOTE: determine the proper DISPLAY variable setting on OSX by launching terminal window in XQuartz and type echo $DISPLAY
